In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import os
import datetime
import numpy as np

#import csv
scores_df=pd.read_csv("resources/merged_df.csv")
scores_df

,Unnamed: 0,Competition Title,Competition Date,FIRST,LAST,Nation,StartNr,Rank,Qualification,Semifinal,...,Quali_Atempts_Tops,Quali_Attempts_Zones,semi_Tops,semi_Zones,semi_Atempts_Tops,semi_Attempts_Zones,Finals_Tops,Finals_Zones,Final_Atempts_Tops,Final_Attempts_Zones
0,0,European Youth Championships (B) - Brixen (ITA...,20 - 22 September 2019,Naile,MEIGNAN,FRA,15.0,1,6T7z99,3T4z55,...,9,9,3,4,5,5,3,4,8,9
1,1,European Youth Championships (B) - Brixen (ITA...,20 - 22 September 2019,Miriam,FOGU,ITA,27.0,2,4T8z814,3T4z55,...,8,4,3,4,5,5,2,4,2,7
2,2,European Youth Championships (B) - Brixen (ITA...,20 - 22 September 2019,Vanda,MICHALKOVA,SVK,48.0,3,6T7z89,3T3z43,...,8,9,3,3,4,3,2,3,2,3
3,3,European Youth Championships (B) - Brixen (ITA...,20 - 22 September 2019,Lola,SAUTIER,FRA,17.0,4,4T6z69,2T3z89,...,6,9,2,3,8,9,1,3,3,8
4,4,European Youth Championships (B) - Brixen (ITA...,20 - 22 September 2019,Polina,KULAGINA,RUS,39.0,5,4T6z611,3T4z76,...,6,1,3,4,7,6,1,3,4,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2428,5427,European Youth Cup (B) - Soure (POR) 2018,5 - 6 May 2018,solene,MOREAU,FRA,44.0,13,5T8z510,NaN,...,3,6,0,0,0,0,0,0,0,0
2429,5428,European Youth Cup (B) - Soure (POR) 2018,5 - 6 May 2018,Lucie,VAILLANT BULTEL,FRA,45.0,14,5T7z99,NaN,...,4,7,0,0,0,0,0,0,0,0
2430,5429,European Youth Cup (B) - Soure (POR) 2018,5 - 6 May 2018,Helena,WALTZ,GER,81.0,15,5T7z1111,NaN,...,5,7,0,0,0,0,0,0,0,0
2431,5430,European Youth Cup (B) - Soure (POR) 2018,5 - 6 May 2018,Marie,COLOT,BEL,10.0,16,5T6z98,NaN,...,0,5,0,0,0,0,0,0,0,0
2432,5431,European Youth Cup (B) - Soure (POR) 2018,5 - 6 May 2018,Ingrid,KINDLIHAGEN,NOR,137.0,17,5T6z1311,NaN,...,0,2,0,0,0,0,0,0,0,0

In [2]:
import pandas as pd
from sqlalchemy import create_engine
# Define the database file path
db_path = 'sqlite:///../Database/climbing.sqlite'
# Create a SQLAlchemy engine
engine = create_engine(db_path)
# Define the SQL query
query = 'SELECT * FROM climbing_table'
# Execute the SQL query and load the results into a pandas DataFrame
df = pd.read_sql(query, engine)
# Print the first 5 rows of the DataFrame
print(df.head())

OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [2]:
scores_df['competitor_id'] = pd.factorize(scores_df['FIRST'] + '_' + scores_df['LAST'])[0] + 1

In [3]:
scores_df.columns

Index(['Unnamed: 0', 'Competition Title', 'Competition Date', 'FIRST', 'LAST',
       'Nation', 'StartNr', 'Rank', 'Qualification', 'Semifinal', 'Final',
       'Category', 'Quali_Tops', 'Quali_Zones', 'Quali_Atempts_Tops',
       'Quali_Attempts_Zones', 'semi_Tops', 'semi_Zones', 'semi_Atempts_Tops',
       'semi_Attempts_Zones', 'Finals_Tops', 'Finals_Zones',
       'Final_Atempts_Tops', 'Final_Attempts_Zones', 'competitor_id'],
      dtype='object')

In [4]:
scores_df=scores_df.drop(columns=["FIRST","LAST","Qualification","Semifinal","Final","Category","Unnamed: 0",'Competition Title'])
scores_df

,Competition Date,Nation,StartNr,Rank,Quali_Tops,Quali_Zones,Quali_Atempts_Tops,Quali_Attempts_Zones,semi_Tops,semi_Zones,semi_Atempts_Tops,semi_Attempts_Zones,Finals_Tops,Finals_Zones,Final_Atempts_Tops,Final_Attempts_Zones,competitor_id
0,20 - 22 September 2019,FRA,15.0,1,6,7,9,9,3,4,5,5,3,4,8,9,1
1,20 - 22 September 2019,ITA,27.0,2,4,8,8,4,3,4,5,5,2,4,2,7,2
2,20 - 22 September 2019,SVK,48.0,3,6,7,8,9,3,3,4,3,2,3,2,3,3
3,20 - 22 September 2019,FRA,17.0,4,4,6,6,9,2,3,8,9,1,3,3,8,4
4,20 - 22 September 2019,RUS,39.0,5,4,6,6,1,3,4,7,6,1,3,4,7,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2428,5 - 6 May 2018,FRA,44.0,13,1,2,3,6,0,0,0,0,0,0,0,0,923
2429,5 - 6 May 2018,FRA,45.0,14,1,2,4,7,0,0,0,0,0,0,0,0,924
2430,5 - 6 May 2018,GER,81.0,15,1,2,5,7,0,0,0,0,0,0,0,0,501
2431,5 - 6 May 2018,BEL,10.0,16,0,2,0,5,0,0,0,0,0,0,0,0,115
2432,5 - 6 May 2018,NOR,137.0,17,0,1,0,2,0,0,0,0,0,0,0,0,25

In [5]:
scores_df.nunique()

Competition Date          16
Nation                    63
StartNr                  544
Rank                      67
Quali_Tops                 9
Quali_Zones                9
Quali_Atempts_Tops        10
Quali_Attempts_Zones      22
semi_Tops                  5
semi_Zones                 5
semi_Atempts_Tops         10
semi_Attempts_Zones       18
Finals_Tops                5
Finals_Zones               5
Final_Atempts_Tops        10
Final_Attempts_Zones      19
competitor_id           1127
dtype: int64

In [6]:
scores_df["Competition Date"].value_counts()

11  - 12 May 2019               328
31 August - 2 September 2018    301
20  - 22 September 2019         282
25  - 26 May 2019               258
27  - 28 April 2019             241
2  - 3 June 2018                211
21  - 22 July 2018              193
1  - 4 November 2018            151
5  - 7 September 2019            91
7  - 11 November 2018            87
22  - 31 August 2019             59
15  - 17 June 2018               59
21  - 26 November 2018           55
9  - 16 August 2018              51
9  - 10 March 2019               49
5  - 6 May 2018                  17
Name: Competition Date, dtype: int64

In [7]:
scores_df["Nation"].value_counts()

ITA    161
FRA    150
AUT    122
BEL    114
GER    107
      ...
KGZ      3
RSA      2
PER      2
NEP      2
MEX      1
Name: Nation, Length: 63, dtype: int64

In [8]:
# nation_series = scores_df["Nation"].value_counts()
# nation_names = nation_series.index.tolist()

In [9]:
# #Create cutoff value for the countries
# nations_to _replace =[]

In [10]:
encoded_df = pd.get_dummies(scores_df, columns=["Nation"])
encoded_df['competition_id'] = pd.factorize(encoded_df["Competition Date"])[0] + 1
encoded_df

,Competition Date,StartNr,Rank,Quali_Tops,Quali_Zones,Quali_Atempts_Tops,Quali_Attempts_Zones,semi_Tops,semi_Zones,semi_Atempts_Tops,...,Nation_SUI,Nation_SVK,Nation_SWE,Nation_THA,Nation_TPE,Nation_TUR,Nation_UKR,Nation_USA,Nation_VEN,competition_id
0,20 - 22 September 2019,15.0,1,6,7,9,9,3,4,5,...,0,0,0,0,0,0,0,0,0,1
1,20 - 22 September 2019,27.0,2,4,8,8,4,3,4,5,...,0,0,0,0,0,0,0,0,0,1
2,20 - 22 September 2019,48.0,3,6,7,8,9,3,3,4,...,0,1,0,0,0,0,0,0,0,1
3,20 - 22 September 2019,17.0,4,4,6,6,9,2,3,8,...,0,0,0,0,0,0,0,0,0,1
4,20 - 22 September 2019,39.0,5,4,6,6,1,3,4,7,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2428,5 - 6 May 2018,44.0,13,1,2,3,6,0,0,0,...,0,0,0,0,0,0,0,0,0,16
2429,5 - 6 May 2018,45.0,14,1,2,4,7,0,0,0,...,0,0,0,0,0,0,0,0,0,16
2430,5 - 6 May 2018,81.0,15,1,2,5,7,0,0,0,...,0,0,0,0,0,0,0,0,0,16
2431,5 - 6 May 2018,10.0,16,0,2,0,5,0,0,0,...,0,0,0,0,0,0,0,0,0,16
2432,5 - 6 May 2018,137.0,17,0,1,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,16

In [11]:
encoded_df.dtypes

Competition Date     object
StartNr             float64
Rank                  int64
Quali_Tops            int64
Quali_Zones           int64
                     ...
Nation_TUR            uint8
Nation_UKR            uint8
Nation_USA            uint8
Nation_VEN            uint8
competition_id        int64
Length: 80, dtype: object

In [12]:
import re

def fix_date(date_string):
    regex_pattern = r"^(\d{1,2})\s-\s\d{1,2}\s(\w+)\s(\d{4})"
    match_obj = re.match(regex_pattern, date_string)

    if match_obj:
        output_str = f"{match_obj.group(1)} {match_obj.group(2)} {match_obj.group(3)}"
        print(output_str)
    else:
        print("No match found")
    return output_str

In [13]:
dates = encoded_df['Competition Date'].str.extractall(r"^(\d{1,2})\s*(-\s*(\d{1,2})\s+)?(\w+)\s+(\d{4})?")
dates = pd.DataFrame(dates)
dates = dates.reset_index().drop(columns=["match", "level_0",1,2]).reset_index()
dates = dates.drop(columns=["index"])
dates.columns=["day","month","year"]
dates["month"]=pd.to_datetime(dates["month"],format="%B")
dates["month"]=dates["month"].dt.month
dates = dates.fillna(9)
dates.astype({'day':'int64','year':'int64'}).dtypes
dates

     day  month  year
0     20      9  2019
1     20      9  2019
2     20      9  2019
3     20      9  2019
4     20      9  2019
...   ..    ...   ...
2428   5      5  2018
2429   5      5  2018
2430   5      5  2018
2431   5      5  2018
2432   5      5  2018

[2433 rows x 3 columns]

In [14]:
merger_dates_df = pd.merge(encoded_df, dates, left_index=True, right_index=True)
df = merger_dates_df.drop(columns=['Competition Date'])

In [15]:
df

,StartNr,Rank,Quali_Tops,Quali_Zones,Quali_Atempts_Tops,Quali_Attempts_Zones,semi_Tops,semi_Zones,semi_Atempts_Tops,semi_Attempts_Zones,...,Nation_THA,Nation_TPE,Nation_TUR,Nation_UKR,Nation_USA,Nation_VEN,competition_id,day,month,year
0,15.0,1,6,7,9,9,3,4,5,5,...,0,0,0,0,0,0,1,20,9,2019
1,27.0,2,4,8,8,4,3,4,5,5,...,0,0,0,0,0,0,1,20,9,2019
2,48.0,3,6,7,8,9,3,3,4,3,...,0,0,0,0,0,0,1,20,9,2019
3,17.0,4,4,6,6,9,2,3,8,9,...,0,0,0,0,0,0,1,20,9,2019
4,39.0,5,4,6,6,1,3,4,7,6,...,0,0,0,0,0,0,1,20,9,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2428,44.0,13,1,2,3,6,0,0,0,0,...,0,0,0,0,0,0,16,5,5,2018
2429,45.0,14,1,2,4,7,0,0,0,0,...,0,0,0,0,0,0,16,5,5,2018
2430,81.0,15,1,2,5,7,0,0,0,0,...,0,0,0,0,0,0,16,5,5,2018
2431,10.0,16,0,2,0,5,0,0,0,0,...,0,0,0,0,0,0,16,5,5,2018
2432,137.0,17,0,1,0,2,0,0,0,0,...,0,0,0,0,0,0,16,5,5,2018

In [16]:
import numpy as np
 
mask = np.column_stack([encoded_df['Competition Date'].str.contains(r"March", na=False) for col in encoded_df])
encoded_df.loc[mask.any(axis=1)]

,Competition Date,StartNr,Rank,Quali_Tops,Quali_Zones,Quali_Atempts_Tops,Quali_Attempts_Zones,semi_Tops,semi_Zones,semi_Atempts_Tops,...,Nation_SUI,Nation_SVK,Nation_SWE,Nation_THA,Nation_TPE,Nation_TUR,Nation_UKR,Nation_USA,Nation_VEN,competition_id
1259,9 - 10 March 2019,201.0,1,0,4,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,7
1260,9 - 10 March 2019,214.0,2,0,3,0,4,0,0,0,...,0,0,0,0,1,0,0,0,0,7
1261,9 - 10 March 2019,222.0,3,0,3,0,6,0,0,0,...,0,0,0,1,0,0,0,0,0,7
1262,9 - 10 March 2019,215.0,4,0,2,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1263,9 - 10 March 2019,219.0,5,0,1,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1264,9 - 10 March 2019,208.0,6,8,8,9,8,4,4,4,...,0,0,0,0,0,0,0,0,0,7
1265,9 - 10 March 2019,211.0,7,8,8,1,10,3,4,9,...,0,0,0,0,0,0,0,0,0,7
1266,9 - 10 March 2019,216.0,8,5,6,9,7,3,4,1,...,0,0,0,0,0,0,0,0,0,7
1267,9 - 10 March 2019,207.0,9,6,6,1,7,3,4,9,...,0,0,0,0,0,0,0,0,0,7
1268,9 - 10 March 2019,202.0,10,7,8,9,9,4,4,6,...,0,0,0,0,0,0,0,0,0,7
1269,9 - 10 March 2019,220.0,11,6,7,1,8,3,4,8,...,0,0,0,0,0,0,0,0,0,7
1270,9 - 10 March 2019,210.0,12,6,8,1,9,2,4,4,...,0,0,0,0,0,0,0,0,0,7
1271,9 - 10 March 2019,221.0,13,7,8,9,8,2,4,6,...,0,0,0,0,0,0,0,0,0,7
1272,9 - 10 March 2019,213.0,14,5,6,5,6,2,3,3,...,0,0,0,0,0,0,0,0,0,7
1273,9 - 10 March 2019,206.0,15,5,7,7,8,1,4,1,...,0,0,0,0,0,0,0,0,0,7
1274,9 - 10 March 2019,212.0,16,8,8,1,8,1,4,2,...,0,0,0,0,0,0,0,0,0,7
1275,9 - 10 March 2019,203.0,17,5,8,7,0,1,4,2,...,0,0,0,0,0,0,0,0,0,7
1276,9 - 10 March 2019,209.0,18,6,7,6,7,1,4,2,...,0,0,0,0,0,0,0,0,0,7
1277,9 - 10 March 2019,218.0,19,6,8,1,10,1,4,2,...,0,0,0,0,0,0,0,0,0,7
1278,9 - 10 March 2019,217.0,20,5,7,8,0,1,4,5,...,0,0,0,0,0,0,0,0,0,7
1279,9 - 10 March 2019,204.0,21,5,7,1,7,1,3,1,...,0,0,0,0,0,0,0,0,0,7
1280,9 - 10 March 2019,205.0,22,7,8,1,9,1,3,2,...,0,0,0,0,0,0,0,0,0,7
1281,9 - 10 March 2019,114.0,1,5,6,1,6,0,4,0,...,0,0,0,0,0,0,0,0,0,7
1282,9 - 10 March 2019,121.0,2,7,8,1,9,0,4,0,...,0,0,0,0,0,0,0,0,0,7
1283,9 - 10 March 2019,123.0,3,5,7,7,8,0,4,0,...,0,0,0,0,0,0,0,0,0,7
1284,9 - 10 March 2019,108.0,4,5,6,1,7,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1285,9 - 10 March 2019,120.0,5,4,7,6,8,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1286,9 - 10 March 2019,103.0,6,4,6,4,6,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1287,9 - 10 March 2019,112.0,7,4,6,5,7,0,0,0,...,0,0,0,0,1,0,0,0,0,7
1288,9 - 10 March 2019,122.0,8,4,6,8,7,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1289,9 - 10 March 2019,119.0,9,4,6,9,8,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1290,9 - 10 March 2019,113.0,10,4,5,7,9,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1291,9 - 10 March 2019,117.0,11,4,5,8,6,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1292,9 - 10 March 2019,102.0,12,4,4,9,4,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1293,9 - 10 March 2019,115.0,13,3,8,6,4,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1294,9 - 10 March 2019,109.0,14,3,7,5,9,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1295,9 - 10 March 2019,101.0,15,3,6,3,6,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1296,9 - 10 March 2019,124.0,16,3,6,4,6,0,0,0,...,0,0,0,0,1,0,0,0,0,7
1297,9 - 10 March 2019,106.0,17,3,6,5,7,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1298,9 - 10 March 2019,116.0,18,3,6,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1299,9 - 10 March 2019,118.0,19,3,6,6,7,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1300,9 - 10 March 2019,104.0,20,3,5,3,6,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1301,9 - 10 March 2019,126.0,21,2,7,2,9,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1302,9 - 10 March 2019,110.0,22,2,6,2,6,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1303,9 - 10 March 2019,127.0,23,2,6,2,8,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1304,9 - 10 March 2019,111.0,23,2,6,2,3,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1305,9 - 10 March 2019,105.0,25,2,6,3,7,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1306,9 - 10 March 2019,107.0,26,2,6,4,8,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1307,9 - 10 March 2019,125.0,27,2,6,4,9,0,0,0,...,0,0,0,0,0,0,0,0,0,7

In [17]:
import numpy as np

# Assume your rank column is named 'rank' in a pandas DataFrame named 'df'
top_n = 6  # Define the number of top ranks you want to set to 1

# Create a new column named 'rank_top' with all values initialized to 0
df['rank_top'] = np.zeros(len(df))

# Set the top 'top_n' ranks to 1 in the 'rank_top' column
df.loc[df['Rank'] <= top_n, 'rank_top'] = 1

In [19]:
df=df.drop(columns=['Rank'])
df

KeyError: "['Rank'] not found in axis"

In [29]:
df = df.dropna()
df

,StartNr,Quali_Tops,Quali_Zones,Quali_Atempts_Tops,Quali_Attempts_Zones,semi_Tops,semi_Zones,semi_Atempts_Tops,semi_Attempts_Zones,Finals_Tops,...,Nation_TPE,Nation_TUR,Nation_UKR,Nation_USA,Nation_VEN,competition_id,day,month,year,rank_top
0,15.0,6,7,9,9,3,4,5,5,3,...,0,0,0,0,0,1,20,9,2019,1.0
1,27.0,4,8,8,4,3,4,5,5,2,...,0,0,0,0,0,1,20,9,2019,1.0
2,48.0,6,7,8,9,3,3,4,3,2,...,0,0,0,0,0,1,20,9,2019,1.0
3,17.0,4,6,6,9,2,3,8,9,1,...,0,0,0,0,0,1,20,9,2019,1.0
4,39.0,4,6,6,1,3,4,7,6,1,...,0,0,0,0,0,1,20,9,2019,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2428,44.0,1,2,3,6,0,0,0,0,0,...,0,0,0,0,0,16,5,5,2018,0.0
2429,45.0,1,2,4,7,0,0,0,0,0,...,0,0,0,0,0,16,5,5,2018,0.0
2430,81.0,1,2,5,7,0,0,0,0,0,...,0,0,0,0,0,16,5,5,2018,0.0
2431,10.0,0,2,0,5,0,0,0,0,0,...,0,0,0,0,0,16,5,5,2018,0.0
2432,137.0,0,1,0,2,0,0,0,0,0,...,0,0,0,0,0,16,5,5,2018,0.0

In [30]:
# Split our preprocessed data into our features and target arrays
y = df.rank_top.values
X = df.drop(columns="rank_top").values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=1, stratify=y)

In [31]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [32]:
len(X_train_scaled[0])

81

In [33]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  51
hidden_nodes_layer2 = 76
hidden_nodes_layer3 = 91
hidden_nodes_layer4 = 6




nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 51)                4182

 dense_1 (Dense)             (None, 76)                3952

 dense_2 (Dense)             (None, 76)                5852

 dense_3 (Dense)             (None, 91)                7007

 dense_4 (Dense)             (None, 6)                 552

 dense_5 (Dense)             (None, 1)                 7

=================================================================
Total params: 21,552
Trainable params: 21,552
Non-trainable params: 0
_________________________________________________________________

In [34]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [35]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
53/53 [==============================] - 1s 2ms/step - loss: 0.5289 - accuracy: 0.7998
Epoch 2/100
53/53 [==============================] - 0s 2ms/step - loss: 0.3758 - accuracy: 0.8489
Epoch 3/100
53/53 [==============================] - 0s 2ms/step - loss: 0.3372 - accuracy: 0.8489
Epoch 4/100
53/53 [==============================] - 0s 2ms/step - loss: 0.3081 - accuracy: 0.8681
Epoch 5/100
53/53 [==============================] - 0s 2ms/step - loss: 0.2895 - accuracy: 0.8849
Epoch 6/100
53/53 [==============================] - 0s 2ms/step - loss: 0.2738 - accuracy: 0.8879
Epoch 7/100
53/53 [==============================] - 0s 2ms/step - loss: 0.2591 - accuracy: 0.8897
Epoch 8/100
53/53 [==============================] - 0s 2ms/step - loss: 0.2450 - accuracy: 0.9035
Epoch 9/100
53/53 [==============================] - 0s 2ms/step - loss: 0.2281 - accuracy: 0.9101
Epoch 10/100
53/53 [==============================] - 0s 2ms/step - loss: 0.2266 - accuracy: 0.9077
Epoch 11/100
53/53 [==============================] - 0s 2ms/step - loss: 0.2151 - accuracy: 0.9113
Epoch 12/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1992 - accuracy: 0.9245
Epoch 13/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1932 - accuracy: 0.9251
Epoch 14/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1897 - accuracy: 0.9227
Epoch 15/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1821 - accuracy: 0.9275
Epoch 16/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1693 - accuracy: 0.9323
Epoch 17/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1584 - accuracy: 0.9347
Epoch 18/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1508 - accuracy: 0.9442
Epoch 19/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1432 - accuracy: 0.9442
Epoch 20/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1365 - accuracy: 0.9472
Epoch 21/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1484 - accuracy: 0.9430
Epoch 22/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1178 - accuracy: 0.9514
Epoch 23/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1119 - accuracy: 0.9520
Epoch 24/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1265 - accuracy: 0.9466
Epoch 25/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1098 - accuracy: 0.9550
Epoch 26/100
53/53 [==============================] - 0s 2ms/step - loss: 0.1019 - accuracy: 0.9616
Epoch 27/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0880 - accuracy: 0.9700
Epoch 28/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0894 - accuracy: 0.9658
Epoch 29/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0742 - accuracy: 0.9718
Epoch 30/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0632 - accuracy: 0.9754
Epoch 31/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0728 - accuracy: 0.9724
Epoch 32/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0608 - accuracy: 0.9790
Epoch 33/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0634 - accuracy: 0.9766
Epoch 34/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0690 - accuracy: 0.9760
Epoch 35/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0720 - accuracy: 0.9760
Epoch 36/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0630 - accuracy: 0.9754
Epoch 37/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0664 - accuracy: 0.9766
Epoch 38/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0540 - accuracy: 0.9796
Epoch 39/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0466 - accuracy: 0.9820
Epoch 40/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0509 - accuracy: 0.9766
Epoch 41/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0575 - accuracy: 0.9766
Epoch 42/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0449 - accuracy: 0.9826
Epoch 43/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0380 - accuracy: 0.9862
Epoch 44/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0378 - accuracy: 0.9874
Epoch 45/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0424 - accuracy: 0.9862
Epoch 46/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0272 - accuracy: 0.9898
Epoch 47/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0275 - accuracy: 0.9886
Epoch 48/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0423 - accuracy: 0.9838
Epoch 49/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0423 - accuracy: 0.9826
Epoch 50/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0277 - accuracy: 0.9898
Epoch 51/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0305 - accuracy: 0.9886
Epoch 52/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0357 - accuracy: 0.9856
Epoch 53/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0351 - accuracy: 0.9868
Epoch 54/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0238 - accuracy: 0.9922
Epoch 55/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0311 - accuracy: 0.9892
Epoch 56/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0247 - accuracy: 0.9904
Epoch 57/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0187 - accuracy: 0.9904
Epoch 58/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0199 - accuracy: 0.9910
Epoch 59/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0285 - accuracy: 0.9898
Epoch 60/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0262 - accuracy: 0.9892
Epoch 61/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0248 - accuracy: 0.9898
Epoch 62/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0186 - accuracy: 0.9934
Epoch 63/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0258 - accuracy: 0.9928
Epoch 64/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0188 - accuracy: 0.9940
Epoch 65/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0188 - accuracy: 0.9946
Epoch 66/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0260 - accuracy: 0.9892
Epoch 67/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0263 - accuracy: 0.9916
Epoch 68/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0271 - accuracy: 0.9874
Epoch 69/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0436 - accuracy: 0.9856
Epoch 70/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0604 - accuracy: 0.9808
Epoch 71/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0248 - accuracy: 0.9910
Epoch 72/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0148 - accuracy: 0.9946
Epoch 73/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0120 - accuracy: 0.9940
Epoch 74/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0143 - accuracy: 0.9952
Epoch 75/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0553 - accuracy: 0.9796
Epoch 76/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0337 - accuracy: 0.9916
Epoch 77/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0162 - accuracy: 0.9958
Epoch 78/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0099 - accuracy: 0.9976
Epoch 79/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0087 - accuracy: 0.9970
Epoch 80/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0086 - accuracy: 0.9958
Epoch 81/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0075 - accuracy: 0.9958
Epoch 82/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0065 - accuracy: 0.9976
Epoch 83/100

53/53 [==============================] - 0s 2ms/step - loss: 0.0080 - accuracy: 0.9964
Epoch 84/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0108 - accuracy: 0.9958
Epoch 85/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0117 - accuracy: 0.9958
Epoch 86/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0105 - accuracy: 0.9946
Epoch 87/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0081 - accuracy: 0.9964
Epoch 88/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0100 - accuracy: 0.9952
Epoch 89/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0158 - accuracy: 0.9940
Epoch 90/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0426 - accuracy: 0.9850
Epoch 91/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0376 - accuracy: 0.9862
Epoch 92/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0241 - accuracy: 0.9916
Epoch 93/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0200 - accuracy: 0.9934
Epoch 94/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0202 - accuracy: 0.9910
Epoch 95/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0231 - accuracy: 0.9916
Epoch 96/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0089 - accuracy: 0.9970
Epoch 97/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0083 - accuracy: 0.9976
Epoch 98/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0063 - accuracy: 0.9976
Epoch 99/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0060 - accuracy: 0.9976
Epoch 100/100
53/53 [==============================] - 0s 2ms/step - loss: 0.0097 - accuracy: 0.9952

In [36]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

18/18 - 0s - loss: 1.7840 - accuracy: 0.8312 - 191ms/epoch - 11ms/step
Loss: 1.7839690446853638, Accuracy: 0.8312388062477112